### ISSUE TITLE
Default API Key should be removed

### ISSUE THREAD

**Issue by bnusunny** [aws-samples/bedrock-access-gateway#10]
We probably don't want to keep this default API key. It is a security risk if people expose this gateway to public internet. 

https://github.com/aws-samples/bedrock-access-gateway/blob/180c199da91ad748bfec274b8cbab54a7db709c5/src/api/setting.py#L3

**Comment by daixba** [comment]
If you follow the deployment guide and set up a private key yourself (as in step 1), this default key won't be used at all.  

Agreed, it's recommended that customer should maintain a private key rather than using the default key for security concern. Default key should only be used for local development purpose.

**Comment by daixba** [comment]
Close for no updates
